#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ioc-cbc-tools
Version  : 2018ww32.3
Release  : 1
URL      : https://github.com/intel/ioc-cbc-tools/archive/2018ww32.3.tar.gz
Source0  : https://github.com/intel/ioc-cbc-tools/archive/2018ww32.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: ioc-cbc-tools-bin
Requires: ioc-cbc-tools-autostart
Requires: ioc-cbc-tools-config
Requires: ioc-cbc-tools-data
Requires: ioc-cbc-tools-license
BuildRequires : acrn-hypervisor-dev

%description
# ioc-cbc-tools
IOC stands for IO controller which is used for automotive system.
CBC stands for carrier board communiction protocol.

%package autostart
Summary: autostart components for the ioc-cbc-tools package.
Group: Default

%description autostart
autostart components for the ioc-cbc-tools package.


%package bin
Summary: bin components for the ioc-cbc-tools package.
Group: Binaries
Requires: ioc-cbc-tools-data
Requires: ioc-cbc-tools-config
Requires: ioc-cbc-tools-license

%description bin
bin components for the ioc-cbc-tools package.


%package config
Summary: config components for the ioc-cbc-tools package.
Group: Default

%description config
config components for the ioc-cbc-tools package.


%package data
Summary: data components for the ioc-cbc-tools package.
Group: Data

%description data
data components for the ioc-cbc-tools package.


%package license
Summary: license components for the ioc-cbc-tools package.
Group: Default

%description license
license components for the ioc-cbc-tools package.


%prep
%setup -q -n ioc-cbc-tools-2018ww32.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533714940
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1533714940
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ioc-cbc-tools
cp LICENSE %{buildroot}/usr/share/doc/ioc-cbc-tools/LICENSE
%make_install
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../u_cbc_attach.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/u_cbc_attach.service
ln -s ../u_cbc_lifecycle.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/u_cbc_lifecycle.service
mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -sf /usr/lib/systemd/system/u_cbc_attach.service %{buildroot}/usr/share/clr-service-restart/u_cbc_attach.service
ln -sf /usr/lib/systemd/system/u_cbc_lifecycle.service %{buildroot}/usr/share/clr-service-restart/u_cbc_lifecycle.service
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/u_cbc_attach.service
/usr/lib/systemd/system/multi-user.target.wants/u_cbc_lifecycle.service

%files bin
%defattr(-,root,root,-)
/usr/bin/u_cbc_attach
/usr/bin/u_cbc_lifecycle

%files config
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/u_cbc_attach.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/u_cbc_lifecycle.service
/usr/lib/systemd/system/u_cbc_attach.service
/usr/lib/systemd/system/u_cbc_lifecycle.service

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/u_cbc_attach.service
/usr/share/clr-service-restart/u_cbc_lifecycle.service
/usr/share/ioc-cbc-tools/cbc_match.txt

%files license
%defattr(-,root,root,-)
/usr/share/doc/ioc-cbc-tools/LICENSE
